server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: spring-boot-dynamic-demo
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowMultiQueries=true&rewriteBatchedStatements=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/spring2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowMultiQueries=true&rewriteBatchedStatements=true
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleted
  mapper-locations: classpath:/mapper/**.xml

logging:
  level:
    ROOT: INFO
    com.dynamic.dynamicdemo: DEBUG
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} - %msg%n'
  file:
    name: ${logging.file.path}/${spring.application.name}.log
    path: /home/logs/${spring.application.name}
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30

#spring:
#  shardingsphere:
#    datasource:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driverClassName: com.mysql.cj.jdbc.Driver
#      names: master,slave0,slave1
#      master:
#        url: jdbc:mysql://127.0.0.1:3306/spring?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=CTT
#        username: root
#        password: root
#      slave0:
#        url: jdbc:mysql://127.0.0.1:3306/sprin1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=CTT
#        username: root
#        password: root
#      slave1:
#        url: jdbc:mysql://127.0.0.1:3306/spring2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=CTT
#        username: root
#        password: root
#    props:
#      sql.show: true
#    masterslave:
#      load-balance-algorithm-type: round_robin
#    sharding:
#      master-slave-rules:
#        master:
#          master-data-source-name: master
#          slave-data-source-names: slave0,slave1