
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    names: master,slave0,slave1
    master:
      url: jdbc:mysql://192.168.0.108:3306/spring?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=CTT
      username: root
      password: root
    slave0:
      url: jdbc:mysql://192.168.0.109:3306/spring?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=CTT
      username: root
      password: root
    slave1:
      url: jdbc:mysql://192.168.0.110:3306/spring?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=CTT
      username: root
      password: root

