
spring:
  datasource:
    names: master,slave0
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.108:3306/spring?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=CTT
      username: root
      password: root
    slave0:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.109:3306/spring?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=CTT
      username: root
      password: root




