spring:
  ### Feign - 当Bean名字一样的时候，允许覆盖注册
  main:
    allow-bean-definition-overriding: true
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver         # psql驱动
    url: jdbc:mysql://${MYSQL_HOST:127.0.01}:${MYSQL_PORT:3306}/${MYSQL_DB:spring}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=CTT
    username: ${MYSQL-USER:root}
    password: ${MYSQL-PWD:root}
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 20MB     # 文件上传大小限制为20MB
      max-request-size: 20MB  # 请求大小限制为20MB